// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientJournal.API.Data;

#nullable disable

namespace PatientJournal.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientJournal.Shared.Models.CaseMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SimulationCaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SimulationCaseId");

                    b.ToTable("CaseMedications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dosage = "5mg",
                            DrugName = "Amlodipine",
                            Frequency = "Daily",
                            Route = "PO",
                            SimulationCaseId = 1
                        },
                        new
                        {
                            Id = 2,
                            Dosage = "500mg",
                            DrugName = "Metformin",
                            Frequency = "Twice daily",
                            Route = "PO",
                            SimulationCaseId = 1
                        },
                        new
                        {
                            Id = 3,
                            Dosage = "0.1 mcg/kg/min",
                            DrugName = "Norepinephrine",
                            Frequency = "Continuous",
                            Route = "IV",
                            SimulationCaseId = 2
                        },
                        new
                        {
                            Id = 4,
                            Dosage = "4.5g",
                            DrugName = "Piperacillin-Tazobactam",
                            Frequency = "Every 6 hours",
                            Route = "IV",
                            SimulationCaseId = 2
                        });
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.NursingIntervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FluidType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FluidVolumeML")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("ValidationWarning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasValid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.SimulationCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraindications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentDiagnoses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoalTimerMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialDiastolicBP")
                        .HasColumnType("int");

                    b.Property<int>("InitialHeartRate")
                        .HasColumnType("int");

                    b.Property<double>("InitialOxygenSaturation")
                        .HasColumnType("float");

                    b.Property<int>("InitialRespiratoryRate")
                        .HasColumnType("int");

                    b.Property<int>("InitialSystolicBP")
                        .HasColumnType("int");

                    b.Property<double>("InitialTemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeacherOnly")
                        .HasColumnType("bit");

                    b.Property<string>("LabValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientAge")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientSex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PatientWeightKg")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergies = "penicillin",
                            Contraindications = "beta-blocker",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            CurrentDiagnoses = "Hypertensive emergency, headache",
                            Description = "Patient presents with severe hypertension and headache.",
                            GoalTimerMinutes = 10,
                            Goals = "Reduce systolic BP below 160 mmHg within 10 minutes",
                            InitialDiastolicBP = 120,
                            InitialHeartRate = 95,
                            InitialOxygenSaturation = 96.0,
                            InitialRespiratoryRate = 18,
                            InitialSystolicBP = 210,
                            InitialTemperatureCelsius = 37.100000000000001,
                            IsActive = false,
                            IsTeacherOnly = true,
                            LabValues = "Creatinine: 110 µmol/L, K+: 4.1 mmol/L",
                            MedicalHistory = "Chronic hypertension, type 2 diabetes",
                            PatientAge = 58,
                            PatientName = "Anna Hansen",
                            PatientSex = "Female",
                            PatientWeightKg = 72.0,
                            Title = "Hypertensive Emergency"
                        },
                        new
                        {
                            Id = 2,
                            Allergies = "sulfonamides",
                            Contraindications = "",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            CurrentDiagnoses = "Septic shock (suspected urinary source)",
                            Description = "Patient with fever, low blood pressure and elevated heart rate.",
                            GoalTimerMinutes = 15,
                            Goals = "Achieve MAP >65 mmHg, administer antibiotics and 30 ml/kg IV fluid within 15 minutes",
                            InitialDiastolicBP = 50,
                            InitialHeartRate = 128,
                            InitialOxygenSaturation = 91.0,
                            InitialRespiratoryRate = 26,
                            InitialSystolicBP = 82,
                            InitialTemperatureCelsius = 39.399999999999999,
                            IsActive = false,
                            IsTeacherOnly = true,
                            LabValues = "WBC: 18.2, Lactate: 4.1 mmol/L, CRP: 320",
                            MedicalHistory = "COPD, prostate cancer",
                            PatientAge = 72,
                            PatientName = "Lars Eriksen",
                            PatientSex = "Male",
                            PatientWeightKg = 85.0,
                            Title = "Septic Shock"
                        });
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.SimulationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SimulationCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SimulationCaseId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.TeacherObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("TeacherObservations");
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "341A5FB36B5039AE25BB5D0A5B90F78A13259825A23C33B58C0A71F1EA13A120",
                            Role = 1,
                            Username = "teacher"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "0D08D34EBA80E6B3644EB1620C9F8499D34D5A49E45A6681CF99D5D297ED6A36",
                            Role = 0,
                            Username = "student"
                        });
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.VitalReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiastolicBP")
                        .HasColumnType("int");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<double>("OxygenSaturation")
                        .HasColumnType("float");

                    b.Property<int>("RespiratoryRate")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SystolicBP")
                        .HasColumnType("int");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("VitalReadings");
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.CaseMedication", b =>
                {
                    b.HasOne("PatientJournal.Shared.Models.SimulationCase", "SimulationCase")
                        .WithMany("Medications")
                        .HasForeignKey("SimulationCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationCase");
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.NursingIntervention", b =>
                {
                    b.HasOne("PatientJournal.Shared.Models.SimulationSession", "Session")
                        .WithMany("Interventions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.SimulationSession", b =>
                {
                    b.HasOne("PatientJournal.Shared.Models.SimulationCase", "SimulationCase")
                        .WithMany("Sessions")
                        .HasForeignKey("SimulationCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationCase");
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.TeacherObservation", b =>
                {
                    b.HasOne("PatientJournal.Shared.Models.SimulationSession", "Session")
                        .WithMany("TeacherObservations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.VitalReading", b =>
                {
                    b.HasOne("PatientJournal.Shared.Models.SimulationSession", "Session")
                        .WithMany("VitalReadings")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.SimulationCase", b =>
                {
                    b.Navigation("Medications");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("PatientJournal.Shared.Models.SimulationSession", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("TeacherObservations");

                    b.Navigation("VitalReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
